- name: Create user - "{{ user.username }}"
  become: true
  ansible.builtin.user:
    name: "{{ user.username }}"
    uid: "{{ user.uid }}"
    system: true
    groups: "{{ user.groups | default([]) }}"
