- name: Copy pve-remove-nag.sh
  become: true
  ansible.builtin.copy:
    src: pve-remove-nag.sh
    dest: /usr/local/bin/pve-remove-nag.sh
    owner: root
    group: root
    mode: '0755'
- name: Insert apt hook
  become: true
  ansible.builtin.copy:
    content: |
      DPkg::Post-Invoke { "/usr/local/bin/pve-remove-nag.sh"; };
    dest: /etc/apt/apt.conf.d/no-nag-script
    owner: root
    group: root
    mode: '0644'
  register: nag_hook
- name: apt update/upgrade
  become: true
  when: nag_hook.changed
  apt:
    update_cache: true
    upgrade: 'yes'
